
name: 'hr_dbt_example'
version: '1.1.5'
config-version: 2

# set up the name for this profile
profile: 'hr_data'

# Tell DBT the path for your DBT model (means View or Table in standard SQL)
model-paths: ["models"]
# Tell DBT the path for your SQL tests
test-paths: ["tests"]

snapshot-paths: ["snapshots"]

# Tell DBT the path to store the compiled SQL and tests
target-path: "target"

# Tell DBT what to clean when running dbt clean
clean-targets:   
    - "target"
    - "dbt_packages"
